/**
 * Deep validation: diff every DF node against the Python engine's
 * output (tests/fixtures/bootstrap-*.json, generated by
 * scripts/generate_fixtures.py).
 *
 * Tolerance: 1e-10 on DF, 1e-12 on parRate. The reference Excel matches
 * to 10 decimal places per ois_pricer's README, so any looser tolerance
 * would mask real drift.
 */

import { describe, expect, it } from "vitest";
import { bootstrapIso } from "../../src/core/bootstrap";
import { extractImpliedPPK } from "../../src/core/implied-ppk";
import type { OISQuote, QuoteSide } from "../../src/core/types";
import { CBRT_MEETING_DATES } from "../../src/data/ppk-dates";
import { DEFAULT_OIS_QUOTES } from "../../src/data/ois-quotes";

import bootstrapBid from "../fixtures/bootstrap-bid.json";
import bootstrapMid from "../fixtures/bootstrap-mid.json";
import bootstrapAsk from "../fixtures/bootstrap-ask.json";
import impliedPpk from "../fixtures/implied-ppk.json";

const QUOTES: OISQuote[] = [...DEFAULT_OIS_QUOTES];

function checkBootstrap(
  fixture: typeof bootstrapMid,
  side: QuoteSide,
): void {
  const res = bootstrapIso(QUOTES, fixture.tradeDate, side);

  expect(res.valueDate).toBe(fixture.valueDate);
  expect(res.nodes).toHaveLength(fixture.nodes.length);

  for (let i = 0; i < fixture.nodes.length; i++) {
    const actual = res.nodes[i];
    const expected = fixture.nodes[i];

    expect(actual.days).toBe(expected.days);
    expect(actual.matDate).toBe(expected.matDate);
    expect(actual.tenor).toBe(expected.tenor);
    expect(actual.df).toBeCloseTo(expected.df, 10);
    expect(actual.parRate).toBeCloseTo(expected.parRate, 12);
  }
}

describe("bootstrap vs Python engine", () => {
  it("matches bid fixture", () => checkBootstrap(bootstrapBid, "bid"));
  it("matches mid fixture", () => checkBootstrap(bootstrapMid, "mid"));
  it("matches ask fixture", () => checkBootstrap(bootstrapAsk, "ask"));
});

describe("implied PPK vs Python engine", () => {
  it("matches meeting forward rates", () => {
    const res = bootstrapIso(QUOTES, impliedPpk.tradeDate, "mid");
    const actual = extractImpliedPPK(res, CBRT_MEETING_DATES);

    expect(actual).toHaveLength(impliedPpk.meetings.length);
    for (let i = 0; i < actual.length; i++) {
      const e = impliedPpk.meetings[i];
      const a = actual[i];
      expect(a.date).toBe(e.date);
      expect(a.daysFromVd).toBe(e.daysFromVd);
      expect(a.periodDays).toBe(e.periodDays);
      expect(a.df).toBeCloseTo(e.df, 10);
      expect(a.forwardRate).toBeCloseTo(e.forwardRate, 12);
    }
  });
});
